CreateObject("WScript.Shell").AppActivate "mathcad"
CreateObject("WScript.Shell").SendKeys "{F10}" 
CreateObject("WScript.Shell").SendKeys "w" 
CreateObject("WScript.Shell").SendKeys "1" 
CreateObject("WScript.Shell").SendKeys "{F10}" 
CreateObject("WScript.Shell").SendKeys "t" 
CreateObject("WScript.Shell").SendKeys "c"
CreateObject("WScript.Shell").SendKeys "w"
